apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: faa4uti3p-nodejs
  janus-idp.io/tekton: faa4uti3p-nodejs
  backstage.io/kubernetes-id: faa4uti3p-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: faa4uti3p-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
